apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nginx
  namespace: prod
  labels:
    app:  nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  nginx
    spec:
      containers:
      - name:  nginx
        image:  nonzzo/nginx:v0.1.2
        ports:
        - containerPort: 80